In [1]:
# Could add other variables
# merge with clean country codes data that you created
# Overlap with status bins

In [2]:
import plotly
plotly.tools.set_credentials_file(username='nimaij', api_key='8m9riv17rh')

In [3]:
import pandas as pd
# contains data for all countries and their GDP in 2014
gdp = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_world_gdp_with_codes.csv')
gdp.head()

          COUNTRY  GDP (BILLIONS) CODE
0     Afghanistan           21.71  AFG
1         Albania           13.40  ALB
2         Algeria          227.80  DZA
3  American Samoa            0.75  ASM
4         Andorra            4.80  AND

In [4]:
# Data contains all loans sorted by country
countrycount = pd.read_csv('/Users/jiaminlim93/Desktop/GA Data Science Course/project/Data Science Project_Jiamin_/countrycount.csv')
#countrycount.head(20)
countrycount.head()

   Unnamed: 0      country   count
0           0  Philippines  213482
1           1        Kenya  113376
2           2         Peru   77816
3           3     Cambodia   60611
4           4  El Salvador   51147

In [5]:
# Cleaning data so country names match with package
countrycount.set_value(11,'country','Bolivia, Plurinational State of')
countrycount.set_value(16,'country','Viet Nam')
countrycount.set_value(20,'country','Tanzania, United Republic of')
countrycount.set_value(31,'country','Palestine, State of')
countrycount.set_value(47,'country','Congo, The Democratic Republic of the')
countrycount.set_value(59,'country',"Lao People's Democratic Republic")
countrycount.set_value(60,'country','Congo')
countrycount.set_value(67,'country',"Moldova, Republic of")
countrycount.set_value(68,'country',"Myanmar")
countrycount.set_value(84,'country',"Saint Vincent and the Grenadines")

countrycount = countrycount.drop(countrycount.index[[57,72,86]]) #removing Kosovo & Cote d'Ivoire & Gaza
countrycount.tail(50)

    Unnamed: 0                                country  count
40          40                          United States   5337
41          41                                Ukraine   4586
42          42                     Dominican Republic   4395
43          43                             Costa Rica   4192
44          44                               Zimbabwe   4173
45          45                                  Yemen   3921
46          46                                   Iraq   3631
47          47  Congo, The Democratic Republic of the   3435
48          48                               Cameroon   3090
49          49                            Timor-Leste   3025
50          50                                  Haiti   2512
51          51                            Afghanistan   2478
52          52                                Albania   2384
53          53                           Burkina Faso   2223
54          54                             Madagascar   2038
55          55                                  Nepal   1890
56          56                                Burundi   1654
58          58                                 Turkey   1191
59          59       Lao People's Democratic Republic   1052
60          60                                  Congo    954
61          61                                  Egypt    926
62          62                                  Chile    917
63          63                                 Zambia    789
64          64                                 Malawi    659
65          65                           South Africa    623
66          66                 Bosnia and Herzegovina    617
67          67                   Moldova, Republic of    510
68          68                                Myanmar    416
69          69                                 Israel    396
70          70                               Suriname    299
71          71                               Bulgaria    282
73          73                              Sri Lanka    255
74          74                                Somalia    234
75          75                                 Belize    219
76          76                        Solomon Islands    198
77          77                                 Panama    192
78          78                                Lesotho    184
79          79                                 Brazil    158
80          80                                  China    120
81          81                               Thailand    112
82          82                                   Chad     69
83          83                            Puerto Rico     27
84          84       Saint Vincent and the Grenadines     20
85          85                             Bangladesh     14
87          87                                Namibia      7
88          88                                Vanuatu      4
89          89                                   Guam      2
90          90                             Mauritania      1
91          91                               Botswana      1
92          92                       Papua New Guinea      1

In [6]:
import pycountry
list(pycountry.countries)

[Country(alpha_2=u'AW', alpha_3=u'ABW', name=u'Aruba', numeric=u'533'),
 Country(alpha_2=u'AF', alpha_3=u'AFG', name=u'Afghanistan', numeric=u'004', official_name=u'Islamic Republic of Afghanistan'),
 Country(alpha_2=u'AO', alpha_3=u'AGO', name=u'Angola', numeric=u'024', official_name=u'Republic of Angola'),
 Country(alpha_2=u'AI', alpha_3=u'AIA', name=u'Anguilla', numeric=u'660'),
 Country(alpha_2=u'AX', alpha_3=u'ALA', name=u'\xc5land Islands', numeric=u'248'),
 Country(alpha_2=u'AL', alpha_3=u'ALB', name=u'Albania', numeric=u'008', official_name=u'Republic of Albania'),
 Country(alpha_2=u'AD', alpha_3=u'AND', name=u'Andorra', numeric=u'020', official_name=u'Principality of Andorra'),
 Country(alpha_2=u'AE', alpha_3=u'ARE', name=u'United Arab Emirates', numeric=u'784'),
 Country(alpha_2=u'AR', alpha_3=u'ARG', name=u'Argentina', numeric=u'032', official_name=u'Argentine Republic'),
 Country(alpha_2=u'AM', alpha_3=u'ARM', name=u'Armenia', numeric=u'051', official_name=u'Republic of Armenia'),
 Country(alpha_2=u'AS', alpha_3=u'ASM', name=u'American Samoa', numeric=u'016'),
 Country(alpha_2=u'AQ', alpha_3=u'ATA', name=u'Antarctica', numeric=u'010'),
 Country(alpha_2=u'TF', alpha_3=u'ATF', name=u'French Southern Territories', numeric=u'260'),
 Country(alpha_2=u'AG', alpha_3=u'ATG', name=u'Antigua and Barbuda', numeric=u'028'),
 Country(alpha_2=u'AU', alpha_3=u'AUS', name=u'Australia', numeric=u'036'),
 Country(alpha_2=u'AT', alpha_3=u'AUT', name=u'Austria', numeric=u'040', official_name=u'Republic of Austria'),
 Country(alpha_2=u'AZ', alpha_3=u'AZE', name=u'Azerbaijan', numeric=u'031', official_name=u'Republic of Azerbaijan'),
 Country(alpha_2=u'BI', alpha_3=u'BDI', name=u'Burundi', numeric=u'108', official_name=u'Republic of Burundi'),
 Country(alpha_2=u'BE', alpha_3=u'BEL', name=u'Belgium', numeric=u'056', official_name=u'Kingdom of Belgium'),
 Country(alpha_2=u'BJ', alpha_3=u'BEN', name=u'Benin', numeric=u'204', official_name=u'Republic of Benin'),
 Country(alpha_2=u'BQ', alpha_3=u'BES', name=u'Bonaire, Sint Eustatius and Saba', numeric=u'535', official_name=u'Bonaire, Sint Eustatius and Saba'),
 Country(alpha_2=u'BF', alpha_3=u'BFA', name=u'Burkina Faso', numeric=u'854'),
 Country(alpha_2=u'BD', alpha_3=u'BGD', name=u'Bangladesh', numeric=u'050', official_name=u"People's Republic of Bangladesh"),
 Country(alpha_2=u'BG', alpha_3=u'BGR', name=u'Bulgaria', numeric=u'100', official_name=u'Republic of Bulgaria'),
 Country(alpha_2=u'BH', alpha_3=u'BHR', name=u'Bahrain', numeric=u'048', official_name=u'Kingdom of Bahrain'),
 Country(alpha_2=u'BS', alpha_3=u'BHS', name=u'Bahamas', numeric=u'044', official_name=u'Commonwealth of the Bahamas'),
 Country(alpha_2=u'BA', alpha_3=u'BIH', name=u'Bosnia and Herzegovina', numeric=u'070', official_name=u'Republic of Bosnia and Herzegovina'),
 Country(alpha_2=u'BL', alpha_3=u'BLM', name=u'Saint Barth\xe9lemy', numeric=u'652'),
 Country(alpha_2=u'BY', alpha_3=u'BLR', name=u'Belarus', numeric=u'112', official_name=u'Republic of Belarus'),
 Country(alpha_2=u'BZ', alpha_3=u'BLZ', name=u'Belize', numeric=u'084'),
 Country(alpha_2=u'BM', alpha_3=u'BMU', name=u'Bermuda', numeric=u'060'),
 Country(alpha_2=u'BO', alpha_3=u'BOL', common_name=u'Bolivia', name=u'Bolivia, Plurinational State of', numeric=u'068', official_name=u'Plurinational State of Bolivia'),
 Country(alpha_2=u'BR', alpha_3=u'BRA', name=u'Brazil', numeric=u'076', official_name=u'Federative Republic of Brazil'),
 Country(alpha_2=u'BB', alpha_3=u'BRB', name=u'Barbados', numeric=u'052'),
 Country(alpha_2=u'BN', alpha_3=u'BRN', name=u'Brunei Darussalam', numeric=u'096'),
 Country(alpha_2=u'BT', alpha_3=u'BTN', name=u'Bhutan', numeric=u'064', official_name=u'Kingdom of Bhutan'),
 Country(alpha_2=u'BV', alpha_3=u'BVT', name=u'Bouvet Island', numeric=u'074'),
 Country(alpha_2=u'BW', alpha_3=u'BWA', name=u'Botswana', numeric=u'072', official_name=u'Republic of Botswana'),
 Country(alpha_2=u'CF', alpha_3=u'CAF', name=u'Central African Republic', numeric=u'140'),
 Country(alpha_2=u'CA', alpha_3=u'CAN', name=u'Canada', numeric=u'124'),
 Country(alpha_2=u'CC', alpha_3=u'CCK', name=u'Cocos (Keeling) Islands', numeric=u'166'),
 Country(alpha_2=u'CH', alpha_3=u'CHE', name=u'Switzerland', numeric=u'756', official_name=u'Swiss Confederation'),
 Country(alpha_2=u'CL', alpha_3=u'CHL', name=u'Chile', numeric=u'152', official_name=u'Republic of Chile'),
 Country(alpha_2=u'CN', alpha_3=u'CHN', name=u'China', numeric=u'156', official_name=u"People's Republic of China"),
 Country(alpha_2=u'CI', alpha_3=u'CIV', name=u"C\xf4te d'Ivoire", numeric=u'384', official_name=u"Republic of C\xf4te d'Ivoire"),
 Country(alpha_2=u'CM', alpha_3=u'CMR', name=u'Cameroon', numeric=u'120', official_name=u'Republic of Cameroon'),
 Country(alpha_2=u'CD', alpha_3=u'COD', name=u'Congo, The Democratic Republic of the', numeric=u'180'),
 Country(alpha_2=u'CG', alpha_3=u'COG', name=u'Congo', numeric=u'178', official_name=u'Republic of the Congo'),
 Country(alpha_2=u'CK', alpha_3=u'COK', name=u'Cook Islands', numeric=u'184'),
 Country(alpha_2=u'CO', alpha_3=u'COL', name=u'Colombia', numeric=u'170', official_name=u'Republic of Colombia'),
 Country(alpha_2=u'KM', alpha_3=u'COM', name=u'Comoros', numeric=u'174', official_name=u'Union of the Comoros'),
 Country(alpha_2=u'CV', alpha_3=u'CPV', name=u'Cabo Verde', numeric=u'132', official_name=u'Republic of Cabo Verde'),
 Country(alpha_2=u'CR', alpha_3=u'CRI', name=u'Costa Rica', numeric=u'188', official_name=u'Republic of Costa Rica'),
 Country(alpha_2=u'CU', alpha_3=u'CUB', name=u'Cuba', numeric=u'192', official_name=u'Republic of Cuba'),
 Country(alpha_2=u'CW', alpha_3=u'CUW', name=u'Cura\xe7ao', numeric=u'531', official_name=u'Cura\xe7ao'),
 Country(alpha_2=u'CX', alpha_3=u'CXR', name=u'Christmas Island', numeric=u'162'),
 Country(alpha_2=u'KY', alpha_3=u'CYM', name=u'Cayman Islands', numeric=u'136'),
 Country(alpha_2=u'CY', alpha_3=u'CYP', name=u'Cyprus', numeric=u'196', official_name=u'Republic of Cyprus'),
 Country(alpha_2=u'CZ', alpha_3=u'CZE', name=u'Czech Republic', numeric=u'203'),
 Country(alpha_2=u'DE', alpha_3=u'DEU', name=u'Germany', numeric=u'276', official_name=u'Federal Republic of Germany'),
 Country(alpha_2=u'DJ', alpha_3=u'DJI', name=u'Djibouti', numeric=u'262', official_name=u'Republic of Djibouti'),
 Country(alpha_2=u'DM', alpha_3=u'DMA', name=u'Dominica', numeric=u'212', official_name=u'Commonwealth of Dominica'),
 Country(alpha_2=u'DK', alpha_3=u'DNK', name=u'Denmark', numeric=u'208', official_name=u'Kingdom of Denmark'),
 Country(alpha_2=u'DO', alpha_3=u'DOM', name=u'Dominican Republic', numeric=u'214'),
 Country(alpha_2=u'DZ', alpha_3=u'DZA', name=u'Algeria', numeric=u'012', official_name=u"People's Democratic Republic of Algeria"),
 Country(alpha_2=u'EC', alpha_3=u'ECU', name=u'Ecuador', numeric=u'218', official_name=u'Republic of Ecuador'),
 Country(alpha_2=u'EG', alpha_3=u'EGY', name=u'Egypt', numeric=u'818', official_name=u'Arab Republic of Egypt'),
 Country(alpha_2=u'ER', alpha_3=u'ERI', name=u'Eritrea', numeric=u'232', official_name=u'the State of Eritrea'),
 Country(alpha_2=u'EH', alpha_3=u'ESH', name=u'Western Sahara', numeric=u'732'),
 Country(alpha_2=u'ES', alpha_3=u'ESP', name=u'Spain', numeric=u'724', official_name=u'Kingdom of Spain'),
 Country(alpha_2=u'EE', alpha_3=u'EST', name=u'Estonia', numeric=u'233', official_name=u'Republic of Estonia'),
 Country(alpha_2=u'ET', alpha_3=u'ETH', name=u'Ethiopia', numeric=u'231', official_name=u'Federal Democratic Republic of Ethiopia'),
 Country(alpha_2=u'FI', alpha_3=u'FIN', name=u'Finland', numeric=u'246', official_name=u'Republic of Finland'),
 Country(alpha_2=u'FJ', alpha_3=u'FJI', name=u'Fiji', numeric=u'242', official_name=u'Republic of Fiji'),
 Country(alpha_2=u'FK', alpha_3=u'FLK', name=u'Falkland Islands (Malvinas)', numeric=u'238'),
 Country(alpha_2=u'FR', alpha_3=u'FRA', name=u'France', numeric=u'250', official_name=u'French Republic'),
 Country(alpha_2=u'FO', alpha_3=u'FRO', name=u'Faroe Islands', numeric=u'234'),
 Country(alpha_2=u'FM', alpha_3=u'FSM', name=u'Micronesia, Federated States of', numeric=u'583', official_name=u'Federated States of Micronesia'),
 Country(alpha_2=u'GA', alpha_3=u'GAB', name=u'Gabon', numeric=u'266', official_name=u'Gabonese Republic'),
 Country(alpha_2=u'GB', alpha_3=u'GBR', name=u'United Kingdom', numeric=u'826', official_name=u'United Kingdom of Great Britain and Northern Ireland'),
 Country(alpha_2=u'GE', alpha_3=u'GEO', name=u'Georgia', numeric=u'268'),
 Country(alpha_2=u'GG', alpha_3=u'GGY', name=u'Guernsey', numeric=u'831'),
 Country(alpha_2=u'GH', alpha_3=u'GHA', name=u'Ghana', numeric=u'288', official_name=u'Republic of Ghana'),
 Country(alpha_2=u'GI', alpha_3=u'GIB', name=u'Gibraltar', numeric=u'292'),
 Country(alpha_2=u'GN', alpha_3=u'GIN', name=u'Guinea', numeric=u'324', official_name=u'Republic of Guinea'),
 Country(alpha_2=u'GP', alpha_3=u'GLP', name=u'Guadeloupe', numeric=u'312'),
 Country(alpha_2=u'GM', alpha_3=u'GMB', name=u'Gambia', numeric=u'270', official_name=u'Islamic Republic of the Gambia'),
 Country(alpha_2=u'GW', alpha_3=u'GNB', name=u'Guinea-Bissau', numeric=u'624', official_name=u'Republic of Guinea-Bissau'),
 Country(alpha_2=u'GQ', alpha_3=u'GNQ', name=u'Equatorial Guinea', numeric=u'226', official_name=u'Republic of Equatorial Guinea'),
 Country(alpha_2=u'GR', alpha_3=u'GRC', name=u'Greece', numeric=u'300', official_name=u'Hellenic Republic'),
 Country(alpha_2=u'GD', alpha_3=u'GRD', name=u'Grenada', numeric=u'308'),
 Country(alpha_2=u'GL', alpha_3=u'GRL', name=u'Greenland', numeric=u'304'),
 Country(alpha_2=u'GT', alpha_3=u'GTM', name=u'Guatemala', numeric=u'320', official_name=u'Republic of Guatemala'),
 Country(alpha_2=u'GF', alpha_3=u'GUF', name=u'French Guiana', numeric=u'254'),
 Country(alpha_2=u'GU', alpha_3=u'GUM', name=u'Guam', numeric=u'316'),
 Country(alpha_2=u'GY', alpha_3=u'GUY', name=u'Guyana', numeric=u'328', official_name=u'Republic of Guyana'),
 Country(alpha_2=u'HK', alpha_3=u'HKG', name=u'Hong Kong', numeric=u'344', official_name=u'Hong Kong Special Administrative Region of China'),
 Country(alpha_2=u'HM', alpha_3=u'HMD', name=u'Heard Island and McDonald Islands', numeric=u'334'),
 Country(alpha_2=u'HN', alpha_3=u'HND', name=u'Honduras', numeric=u'340', official_name=u'Republic of Honduras'),
 Country(alpha_2=u'HR', alpha_3=u'HRV', name=u'Croatia', numeric=u'191', official_name=u'Republic of Croatia'),
 Country(alpha_2=u'HT', alpha_3=u'HTI', name=u'Haiti', numeric=u'332', official_name=u'Republic of Haiti'),
 Country(alpha_2=u'HU', alpha_3=u'HUN', name=u'Hungary', numeric=u'348', official_name=u'Hungary'),
 Country(alpha_2=u'ID', alpha_3=u'IDN', name=u'Indonesia', numeric=u'360', official_name=u'Republic of Indonesia'),
 Country(alpha_2=u'IM', alpha_3=u'IMN', name=u'Isle of Man', numeric=u'833'),
 Country(alpha_2=u'IN', alpha_3=u'IND', name=u'India', numeric=u'356', official_name=u'Republic of India'),
 Country(alpha_2=u'IO', alpha_3=u'IOT', name=u'British Indian Ocean Territory', numeric=u'086'),
 Country(alpha_2=u'IE', alpha_3=u'IRL', name=u'Ireland', numeric=u'372'),
 Country(alpha_2=u'IR', alpha_3=u'IRN', name=u'Iran, Islamic Republic of', numeric=u'364', official_name=u'Islamic Republic of Iran'),
 Country(alpha_2=u'IQ', alpha_3=u'IRQ', name=u'Iraq', numeric=u'368', official_name=u'Republic of Iraq'),
 Country(alpha_2=u'IS', alpha_3=u'ISL', name=u'Iceland', numeric=u'352', official_name=u'Republic of Iceland'),
 Country(alpha_2=u'IL', alpha_3=u'ISR', name=u'Israel', numeric=u'376', official_name=u'State of Israel'),
 Country(alpha_2=u'IT', alpha_3=u'ITA', name=u'Italy', numeric=u'380', official_name=u'Italian Republic'),
 Country(alpha_2=u'JM', alpha_3=u'JAM', name=u'Jamaica', numeric=u'388'),
 Country(alpha_2=u'JE', alpha_3=u'JEY', name=u'Jersey', numeric=u'832'),
 Country(alpha_2=u'JO', alpha_3=u'JOR', name=u'Jordan', numeric=u'400', official_name=u'Hashemite Kingdom of Jordan'),
 Country(alpha_2=u'JP', alpha_3=u'JPN', name=u'Japan', numeric=u'392'),
 Country(alpha_2=u'KZ', alpha_3=u'KAZ', name=u'Kazakhstan', numeric=u'398', official_name=u'Republic of Kazakhstan'),
 Country(alpha_2=u'KE', alpha_3=u'KEN', name=u'Kenya', numeric=u'404', official_name=u'Republic of Kenya'),
 Country(alpha_2=u'KG', alpha_3=u'KGZ', name=u'Kyrgyzstan', numeric=u'417', official_name=u'Kyrgyz Republic'),
 Country(alpha_2=u'KH', alpha_3=u'KHM', name=u'Cambodia', numeric=u'116', official_name=u'Kingdom of Cambodia'),
 Country(alpha_2=u'KI', alpha_3=u'KIR', name=u'Kiribati', numeric=u'296', official_name=u'Republic of Kiribati'),
 Country(alpha_2=u'KN', alpha_3=u'KNA', name=u'Saint Kitts and Nevis', numeric=u'659'),
 Country(alpha_2=u'KR', alpha_3=u'KOR', name=u'Korea, Republic of', numeric=u'410'),
 Country(alpha_2=u'KW', alpha_3=u'KWT', name=u'Kuwait', numeric=u'414', official_name=u'State of Kuwait'),
 Country(alpha_2=u'LA', alpha_3=u'LAO', name=u"Lao People's Democratic Republic", numeric=u'418'),
 Country(alpha_2=u'LB', alpha_3=u'LBN', name=u'Lebanon', numeric=u'422', official_name=u'Lebanese Republic'),
 Country(alpha_2=u'LR', alpha_3=u'LBR', name=u'Liberia', numeric=u'430', official_name=u'Republic of Liberia'),
 Country(alpha_2=u'LY', alpha_3=u'LBY', name=u'Libya', numeric=u'434', official_name=u'Libya'),
 Country(alpha_2=u'LC', alpha_3=u'LCA', name=u'Saint Lucia', numeric=u'662'),
 Country(alpha_2=u'LI', alpha_3=u'LIE', name=u'Liechtenstein', numeric=u'438', official_name=u'Principality of Liechtenstein'),
 Country(alpha_2=u'LK', alpha_3=u'LKA', name=u'Sri Lanka', numeric=u'144', official_name=u'Democratic Socialist Republic of Sri Lanka'),
 Country(alpha_2=u'LS', alpha_3=u'LSO', name=u'Lesotho', numeric=u'426', official_name=u'Kingdom of Lesotho'),
 Country(alpha_2=u'LT', alpha_3=u'LTU', name=u'Lithuania', numeric=u'440', official_name=u'Republic of Lithuania'),
 Country(alpha_2=u'LU', alpha_3=u'LUX', name=u'Luxembourg', numeric=u'442', official_name=u'Grand Duchy of Luxembourg'),
 Country(alpha_2=u'LV', alpha_3=u'LVA', name=u'Latvia', numeric=u'428', official_name=u'Republic of Latvia'),
 Country(alpha_2=u'MO', alpha_3=u'MAC', name=u'Macao', numeric=u'446', official_name=u'Macao Special Administrative Region of China'),
 Country(alpha_2=u'MF', alpha_3=u'MAF', name=u'Saint Martin (French part)', numeric=u'663'),
 Country(alpha_2=u'MA', alpha_3=u'MAR', name=u'Morocco', numeric=u'504', official_name=u'Kingdom of Morocco'),
 Country(alpha_2=u'MC', alpha_3=u'MCO', name=u'Monaco', numeric=u'492', official_name=u'Principality of Monaco'),
 Country(alpha_2=u'MD', alpha_3=u'MDA', common_name=u'Moldova', name=u'Moldova, Republic of', numeric=u'498', official_name=u'Republic of Moldova'),
 Country(alpha_2=u'MG', alpha_3=u'MDG', name=u'Madagascar', numeric=u'450', official_name=u'Republic of Madagascar'),
 Country(alpha_2=u'MV', alpha_3=u'MDV', name=u'Maldives', numeric=u'462', official_name=u'Republic of Maldives'),
 Country(alpha_2=u'MX', alpha_3=u'MEX', name=u'Mexico', numeric=u'484', official_name=u'United Mexican States'),
 Country(alpha_2=u'MH', alpha_3=u'MHL', name=u'Marshall Islands', numeric=u'584', official_name=u'Republic of the Marshall Islands'),
 Country(alpha_2=u'MK', alpha_3=u'MKD', name=u'Macedonia, Republic of', numeric=u'807', official_name=u'The Former Yugoslav Republic of Macedonia'),
 Country(alpha_2=u'ML', alpha_3=u'MLI', name=u'Mali', numeric=u'466', official_name=u'Republic of Mali'),
 Country(alpha_2=u'MT', alpha_3=u'MLT', name=u'Malta', numeric=u'470', official_name=u'Republic of Malta'),
 Country(alpha_2=u'MM', alpha_3=u'MMR', name=u'Myanmar', numeric=u'104', official_name=u'Republic of Myanmar'),
 Country(alpha_2=u'ME', alpha_3=u'MNE', name=u'Montenegro', numeric=u'499', official_name=u'Montenegro'),
 Country(alpha_2=u'MN', alpha_3=u'MNG', name=u'Mongolia', numeric=u'496'),
 Country(alpha_2=u'MP', alpha_3=u'MNP', name=u'Northern Mariana Islands', numeric=u'580', official_name=u'Commonwealth of the Northern Mariana Islands'),
 Country(alpha_2=u'MZ', alpha_3=u'MOZ', name=u'Mozambique', numeric=u'508', official_name=u'Republic of Mozambique'),
 Country(alpha_2=u'MR', alpha_3=u'MRT', name=u'Mauritania', numeric=u'478', official_name=u'Islamic Republic of Mauritania'),
 Country(alpha_2=u'MS', alpha_3=u'MSR', name=u'Montserrat', numeric=u'500'),
 Country(alpha_2=u'MQ', alpha_3=u'MTQ', name=u'Martinique', numeric=u'474'),
 Country(alpha_2=u'MU', alpha_3=u'MUS', name=u'Mauritius', numeric=u'480', official_name=u'Republic of Mauritius'),
 Country(alpha_2=u'MW', alpha_3=u'MWI', name=u'Malawi', numeric=u'454', official_name=u'Republic of Malawi'),
 Country(alpha_2=u'MY', alpha_3=u'MYS', name=u'Malaysia', numeric=u'458'),
 Country(alpha_2=u'YT', alpha_3=u'MYT', name=u'Mayotte', numeric=u'175'),
 Country(alpha_2=u'NA', alpha_3=u'NAM', name=u'Namibia', numeric=u'516', official_name=u'Republic of Namibia'),
 Country(alpha_2=u'NC', alpha_3=u'NCL', name=u'New Caledonia', numeric=u'540'),
 Country(alpha_2=u'NE', alpha_3=u'NER', name=u'Niger', numeric=u'562', official_name=u'Republic of the Niger'),
 Country(alpha_2=u'NF', alpha_3=u'NFK', name=u'Norfolk Island', numeric=u'574'),
 Country(alpha_2=u'NG', alpha_3=u'NGA', name=u'Nigeria', numeric=u'566', official_name=u'Federal Republic of Nigeria'),
 Country(alpha_2=u'NI', alpha_3=u'NIC', name=u'Nicaragua', numeric=u'558', official_name=u'Republic of Nicaragua'),
 Country(alpha_2=u'NU', alpha_3=u'NIU', name=u'Niue', numeric=u'570', official_name=u'Niue'),
 Country(alpha_2=u'NL', alpha_3=u'NLD', name=u'Netherlands', numeric=u'528', official_name=u'Kingdom of the Netherlands'),
 Country(alpha_2=u'NO', alpha_3=u'NOR', name=u'Norway', numeric=u'578', official_name=u'Kingdom of Norway'),
 Country(alpha_2=u'NP', alpha_3=u'NPL', name=u'Nepal', numeric=u'524', official_name=u'Federal Democratic Republic of Nepal'),
 Country(alpha_2=u'NR', alpha_3=u'NRU', name=u'Nauru', numeric=u'520', official_name=u'Republic of Nauru'),
 Country(alpha_2=u'NZ', alpha_3=u'NZL', name=u'New Zealand', numeric=u'554'),
 Country(alpha_2=u'OM', alpha_3=u'OMN', name=u'Oman', numeric=u'512', official_name=u'Sultanate of Oman'),
 Country(alpha_2=u'PK', alpha_3=u'PAK', name=u'Pakistan', numeric=u'586', official_name=u'Islamic Republic of Pakistan'),
 Country(alpha_2=u'PA', alpha_3=u'PAN', name=u'Panama', numeric=u'591', official_name=u'Republic of Panama'),
 Country(alpha_2=u'PN', alpha_3=u'PCN', name=u'Pitcairn', numeric=u'612'),
 Country(alpha_2=u'PE', alpha_3=u'PER', name=u'Peru', numeric=u'604', official_name=u'Republic of Peru'),
 Country(alpha_2=u'PH', alpha_3=u'PHL', name=u'Philippines', numeric=u'608', official_name=u'Republic of the Philippines'),
 Country(alpha_2=u'PW', alpha_3=u'PLW', name=u'Palau', numeric=u'585', official_name=u'Republic of Palau'),
 Country(alpha_2=u'PG', alpha_3=u'PNG', name=u'Papua New Guinea', numeric=u'598', official_name=u'Independent State of Papua New Guinea'),
 Country(alpha_2=u'PL', alpha_3=u'POL', name=u'Poland', numeric=u'616', official_name=u'Republic of Poland'),
 Country(alpha_2=u'PR', alpha_3=u'PRI', name=u'Puerto Rico', numeric=u'630'),
 Country(alpha_2=u'KP', alpha_3=u'PRK', name=u"Korea, Democratic People's Republic of", numeric=u'408', official_name=u"Democratic People's Republic of Korea"),
 Country(alpha_2=u'PT', alpha_3=u'PRT', name=u'Portugal', numeric=u'620', official_name=u'Portuguese Republic'),
 Country(alpha_2=u'PY', alpha_3=u'PRY', name=u'Paraguay', numeric=u'600', official_name=u'Republic of Paraguay'),
 Country(alpha_2=u'PS', alpha_3=u'PSE', name=u'Palestine, State of', numeric=u'275', official_name=u'the State of Palestine'),
 Country(alpha_2=u'PF', alpha_3=u'PYF', name=u'French Polynesia', numeric=u'258'),
 Country(alpha_2=u'QA', alpha_3=u'QAT', name=u'Qatar', numeric=u'634', official_name=u'State of Qatar'),
 Country(alpha_2=u'RE', alpha_3=u'REU', name=u'R\xe9union', numeric=u'638'),
 Country(alpha_2=u'RO', alpha_3=u'ROU', name=u'Romania', numeric=u'642'),

In [7]:
# Adding on country codes to the country count file
code = []

# For each row in the column
for row in countrycount['country']:
    country = pycountry.countries.get(name=row)
    code.append(country.alpha_3)

countrycount['CODE'] = code
countrycount.to_csv('countrycountwithcode.csv')
#countrycount.head()

In [8]:
# Creating a full dataset so all the map lines come up in the choropleth
total = pd.merge(gdp, countrycount, on='CODE', how='left')
total = total.drop(total.columns[[3,4]], axis=1)
total = total[['COUNTRY', 'CODE', 'GDP (BILLIONS)', 'count']]
total['count'].fillna(0,inplace=True)
total.head(10)
total.to_csv('total.csv')

In [9]:
total.head()

          COUNTRY CODE  GDP (BILLIONS)   count
0     Afghanistan  AFG           21.71  2478.0
1         Albania  ALB           13.40  2384.0
2         Algeria  DZA          227.80     0.0
3  American Samoa  ASM            0.75     0.0
4         Andorra  AND            4.80     0.0

In [11]:
# Plotting a world map
import plotly.plotly as py
import pandas as pd

df = pd.read_csv('/Users/jiaminlim93/Desktop/GA Data Science Course/project/Data Science Project_Jiamin_/total.csv')

data = [ dict(
        type = 'choropleth',
        locations = df['CODE'],
        z = df['count'],
        text = df['COUNTRY'],
        colorscale = [
        # Let first 10% (0.1) of the values have color rgb(0, 0, 0)
        [0, 'rgb(0, 0, 0)'],
        [0.1, 'rgb(0, 0, 0)'],

        # Let values between 10-20% of the min and max of z
        # have color rgb(20, 20, 20)
        [0.1, 'rgb(20, 20, 20)'],
        [0.2, 'rgb(20, 20, 20)'],

        # Values between 20-30% of the min and max of z
        # have color rgb(40, 40, 40)
        [0.2, 'rgb(40, 40, 40)'],
        [0.3, 'rgb(40, 40, 40)'],

        [0.3, 'rgb(60, 60, 60)'],
        [0.4, 'rgb(60, 60, 60)'],

        [0.4, 'rgb(80, 80, 80)'],
        [0.5, 'rgb(80, 80, 80)'],

        [0.5, 'rgb(100, 100, 100)'],
        [0.6, 'rgb(100, 100, 100)'],

        [0.6, 'rgb(120, 120, 120)'],
        [0.7, 'rgb(120, 120, 120)'],

        [0.7, 'rgb(140, 140, 140)'],
        [0.8, 'rgb(140, 140, 140)'],

        [0.8, 'rgb(160, 160, 160)'],
        [0.9, 'rgb(160, 160, 160)'],

        [0.9, 'rgb(180, 180, 180)'],
        [1.0, 'rgb(360, 360, 360)']],
        autocolorscale = False,
        reversescale = True,
        marker = dict(
            line = dict (
                color = 'rgb(180,180,180)',
                width = 0.5
            ) ),
        colorbar = dict(
            autotick = False,
            tickprefix = '',
            title = 'Loan count'),
      ) ]

layout = dict(
    title = 'Loan Count by Country<br>Source:\
            <a href="https://www.kivatools.com/">\
            Kiva</a>',
    geo = dict(
        showframe = False,
        showcoastlines = False,
        projection = dict(
            type = 'Mercator'
        )
    )
)

fig = dict( data=data, layout=layout )
py.iplot( fig, validate=False, filename='d3-world-map' )